### ISSUE TITLE
Create Pre-editing/copyediting checklist page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#9]
- [x] Exeter to come up with pre-editing checklist
- [x] Create page 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Share page with Exeter and invite feedback

### Definition of done
- [x] Page completed
- [x] Team reviewed and approved page?

**Comment by JGilbert-eLife** [comment]
I have copied Exeter's list into https://app.gitbook.com/@elifesciences/s/productionhowto/checklists/processing and have started editing it to add in useful links.

**Comment by JGilbert-eLife** [comment]
I think I have completed the pre-editing list, so feedback on that would be great!

https://app.gitbook.com/@elifesciences/s/productionhowto/checklists/processing

I've emailed Exeter about the copy-editing list to make sure I haven't listed out things that are covered by automated tools.

**Comment by FAtherden-eLife** [comment]
> If there is a mismatch between the author names in the export XML and the Manuscript file,  the Manuscript should be followed.

Is it worth mentioning the same is true for affiliations, present addresses and corresponding author status?

**Comment by FAtherden-eLife** [comment]
> Each keyword in keyword section should be entered separatly, not grouped together.

Typo - separatly.

**Comment by FAtherden-eLife** [comment]
> For Insight articles, related articles reference should have eLocation ID.

And add DOI based on eLocation ID.

**Comment by FAtherden-eLife** [comment]
> Footnotes to the main text are not allowed. Any such footnotes should be incorporated as a bracketed statement at the point where they are cited in the text. An author query should be added to confirm this is acceptable: "As eLife does not support footnotes to the main text, we have integrated this note into the text at the point it was cited. Please confirm this is acceptable."

Is it worth formatting the author query as a bullet point, as used elsewhere in other pages?

**Comment by Melissa37** [comment]
>Check and separate multiple grant numbers for the same funder in the funding table.

I think this could be clearer:

>If there ate multiple grant numbers for the same funder in the funding table, repeat the funder name so each grant number is contained in a unique entry

? Or something like that!

**Comment by FAtherden-eLife** [comment]
Suggest adding to the PDF section something about checking the blue background in appendices appears as expected. I've seen white blocks appearing randomly quite a lot recently (especially in tables).

**Comment by Melissa37** [comment]
>Check if the funder gets validated against the Open Funder Registry, if not do a cursory check online to identify a correct funder name (see Funding for more information).

Suggest changing to:

Check if the funder validates against the Open Funder Registry, if not do a cursory check online to identify a correct funder name (see Funding for more information).

**Comment by Melissa37** [comment]
>Raise an author query if complete information is not provided - author names or grant number


I did not realised we AQ if there was not a grant number for a funding entry?

**Comment by JGilbert-eLife** [comment]
> > Raise an author query if complete information is not provided - author names or grant number
> 
> I did not realised we AQ if there was not a grant number for a funding entry?

Actually, we don't need to - that's straight from what Exeter provided to me, so we should correct that.

**Comment by Melissa37** [comment]
>Check that the competing interests (if present) and funder links from page 1 go to the correct page.
Check that the eLife digest section is included (for articles that have a digest).

We should check with Ayyappan whether this still needs to be done, this feels like something hanging over from the beginning. We don't do that do we?

**Comment by Melissa37** [comment]
>Double check the tables and raise a query if the colours given in the table are against the eLife style.

Why are they doing this on the PDF and not in Kriya itself?

**Comment by Melissa37** [comment]
PDF

They should be checking the layout - that's the main thing! No widowed lines at ends of articles or between assets; no massive spaces around figure; no figure legends that start on a new page or have 1 line of the figure legend hanging at the top of a new page etc

**Comment by Melissa37** [comment]
>Make sure that each display equation as an equation ID.

Typo has not as

**Comment by FAtherden-eLife** [comment]
> PDF
> 7. Check that the figures are legible in the PDFs. If they are not, the author should be queried to provide higher resolution images.

Check that Figures appear in the correct sequence and, as far as possible, that they display close to their first citations.

**Comment by Melissa37** [comment]
>All the equations should be formatted the same as in the exported merged PDF file.


Should this be more explicit - cross check every equation with source file to ensure displayed and formatted correctly and nothing has been corrupted or changed in the conversion process?

**Comment by FAtherden-eLife** [comment]
> 7. Check for any missing panel labels in the figure legends or images. If the image has panel labels but the legend does not, the authors should be asked to add panel labels to the legend. If the legend has panel labels but the image does not, the authors should be asked to provide a new image file. See the Figures and figure supplements page for more information.

Was this included in the list that Exeter sent over as a pre-editing task? I would expect (perhaps incorrectly) this to be a copyediting task. Just curious.

**Comment by Melissa37** [comment]
Copy editing:
Each new sentence in a figure legend should start with a capital letter

(this is something I've seen missed a lot)

**Comment by Melissa37** [comment]
Copy editing:
Each new sentence in a figure legend should start with a capital letter

(this is something I've seen missed a lot)

**Comment by FAtherden-eLife** [comment]
> Article details page

Author contributions should be semi-colon separated. Each one should be in sentence case.

**Comment by FAtherden-eLife** [comment]
> Content page

Section titles should be made sentence case.

**Comment by FAtherden-eLife** [comment]
> Content page

'i.e.' and 'e.g.' outside of parentheses changes to that is or similar.

**Comment by FAtherden-eLife** [comment]
> Content page

Do we need ordinals spelled out - first instead of 1st? Up to ninth according to the spreadsheet.

**Comment by FAtherden-eLife** [comment]
'and' instead of ampersand

**Comment by JGilbert-eLife** [comment]
> > 1. Check for any missing panel labels in the figure legends or images. If the image has panel labels but the legend does not, the authors should be asked to add panel labels to the legend. If the legend has panel labels but the image does not, the authors should be asked to provide a new image file. See the Figures and figure supplements page for more information.
> 
> Was this included in the list that Exeter sent over as a pre-editing task? I would expect (perhaps incorrectly) this to be a copyediting task. Just curious.

I added this. I assumed pre-editing would be better placement, but don't really mind.

**Comment by JGilbert-eLife** [comment]
> > Content page
> 
> Section titles should be made sentence case.

I thought I covered this?  "Headers and titles for figures, tables, source data etc. should be in sentence case."

**Comment by JGilbert-eLife** [comment]
> Copy editing:
> Each new sentence in a figure legend should start with a capital letter
> 
> (this is something I've seen missed a lot)

But this is covered by the schematron. Shouldn't that be covered in the figures page?

**Comment by FAtherden-eLife** [comment]
>> Content page

>> Section titles should be made sentence case.

> I thought I covered this? "Headers and titles for figures, tables, source data etc. should be in sentence case." Edited for clarity.

Ah sorry, I think I just missed this.

**Comment by naushinthomson** [comment]
>7. Check and separate multiple grant numbers for the same funder in the funding table.

Suggest adding a link to [multiple grant references in one entry](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/funding-information#multiple-grant-references-in-one-entry)

**Comment by naushinthomson** [comment]
>13. If a URL is not present, add the identifier to the URL provided on the Data availability page (or query the author if the database is not in the reference table).

Suggest adding a link to [database examples](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/data-availability#database-examples).

**Comment by naushinthomson** [comment]
>PDF

Suggest adding something about avoiding unnecessary splitting of content over two pages (e.g. one sentence of a figure caption on the page after the figure, dataset table going over two pages unnecessarily, materials and methods section at the end of one page and KRT at the beginning of the next page - although this last one may already be covered in the [issue](https://gitlab.com/ExeterPremedia/Customers/eLife-1.5/-/issues/383) about this)

**Comment by naushinthomson** [comment]
I think that's it from me - the only other thing is we are now making all hyperlinks bold just to make them stand out a bit as hyperlinks!

**Comment by JGilbert-eLife** [comment]
> > 1. If a URL is not present, add the identifier to the URL provided on the Data availability page (or query the author if the database is not in the reference table).
> 
> Suggest adding a link to [database examples](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/data-availability#database-examples).

I did! That's where the link in that line goes.

**Comment by naushinthomson** [comment]
> > > 1. If a URL is not present, add the identifier to the URL provided on the Data availability page (or query the author if the database is not in the reference table).
> > 
> > 
> > Suggest adding a link to [database examples](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/data-availability#database-examples).
> 
> I did! That's where the link in that line goes.

Oh I don't know how I missed that sorry!

**Comment by naushinthomson** [comment]
Just had another thought, I don't know if this is the right place for it but should we include making sure that source code is zipped up in this list?

**Comment by bcollins14** [comment]
Who would be expected to check for data on request in the DAS or in the main text?

**Comment by bcollins14** [comment]
`For Insight articles, related article reference(s) must have both an eLocation ID and a DOI.`

Is it worth mentioning that they should also double check the author list/article title is also correct following previous errors with having to copy and paste this information?

**Comment by bcollins14** [comment]
`Check for any 'no entity' character errors (on Greek letters, accented characters, maths terms etc).`

My recent occurrence of this was on the figures PDF, would they be checking this at pre-editing or just the article PDF?

**Comment by bcollins14** [comment]
And finally, I'm not sure if I missed it but do we need to include removing the full stop after Inc?

**Comment by JGilbert-eLife** [comment]
> And finally, I'm not sure if I missed it but do we need to include removing the full stop after Inc?

This is a schematron check, that I don't think needs to be covered here.

I've updated the page to cover (hopefully) everything the pre-editors and copy-editors need to do. Please let me know if I've missed anything else, or if anything is unclear.

https://app.gitbook.com/@elifesciences/s/productionhowto/checklists/processing

**Comment by FAtherden-eLife** [comment]
Looks good :+1: - thanks James.

**Comment by Melissa37** [comment]
@JGilbert-eLife can we add to the Kriya 2 list of actions:
>Each research organism in the research organisms section should be entered separately, not grouped together (sometimes multiple terms will be pulled into one entry).

They are in different fields in EJP so this is a technical issue Ayyappan should be able to. fix for them?

**Comment by Melissa37** [comment]
>Each keyword in the keyword section should be entered separately, not grouped together.

Again, they are in different fields in EJP so this is a technical issue Ayyappan should be able to fix for them?

**Comment by Melissa37** [comment]
>Content page

Should there be a "check export XML file to ensure all assets have been loaded"?

They sometimes miss this and I don't think it is fully automated :-)

**Comment by Melissa37** [comment]
>Check for any 'no entity' character errors (on Greek letters, accented characters, maths terms etc) in either PDF.

It might be useful to show a screenshot of what this looks like?

**Comment by Melissa37** [comment]
>Check that the blue background and border in appendices is consistent. Any white gaps in this background, for example around tables, should be corrected.


Will be redundant soon :-)

**Comment by Melissa37** [comment]
>For LaTex articles, this query is mandatory:


Suggest adding "author" before query

**Comment by Melissa37** [comment]
>Single quotation marks should be used for emphasis ('some text') . Double quotation marks should be used for direct quotes ("a quote from another article").

Extra space in front of full stop ('some text') .

**Comment by Melissa37** [comment]
>All trademark ™, registered ® and copyright © symbols should be deleted.

Oxford comma required

**Comment by Melissa37** [comment]
>'&' should be changed to 'and' if used as part of a sentence. '&' should be left if used as part of a name such as R&D' or 'Texas A&M University'.

Required '  before R&D'

**Comment by Melissa37** [comment]
>For figures, tables and supplementary files:

Oxford comma required

**Comment by JGilbert-eLife** [comment]
> > Content page
> 
> Should there be a "check export XML file to ensure all assets have been loaded"?
> 
> They sometimes miss this and I don't think it is fully automated :-)

This is what I was going for with "Make sure that all files in the export package have been typeset, even if a title/legend is missing. Query the author for any missing titles." Is that unclear?

**Comment by JGilbert-eLife** [comment]
> @JGilbert-eLife can we add to the Kriya 2 list of actions:
> 

Where should that go? I think there was a link to the right board but I seem to have misplaced it (as usual).

**Comment by naushinthomson** [comment]
For 'Double check the tables and raise a query if the colours given in the table are against the eLife style.' 
Suggest adding a link to [allowed colours in tables](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/allowed-assets/tables#allowed-colours-in-tables)

**Comment by naushinthomson** [comment]
Do we need to specifically say on this page that code should be forked and software references should be added where needed? And also adding in figure permissions if required?

**Comment by JGilbert-eLife** [comment]
> And also adding in figure permissions if required?

For now, I think leaving the figure permissions to be covered by the prod notes and the schematron is fine. I've added the code forking stuff to the article details/DAS checks. Again, the schematron should highlight this elsewhere.

**Comment by JGilbert-eLife** [comment]
> And finally, I'm not sure if I missed it but do we need to include removing the full stop after Inc?

This is not actually on our style guide. Hmm. But it is specifically covered by the schematron, so I'm not sure it needs to go on this page. I'll add it under punctuation for the CE anyway, just to be sure.

**Comment by JGilbert-eLife** [comment]
Shared with Exeter - probably need to add a pre-editing item about checking for tables in Figures/Figure supplements once they have checked everything.

**Comment by JGilbert-eLife** [comment]
Exeter have approved, done!
